spring:
  application:
    name: payment-orchestrator-engine
  threads:
    virtual:
      enabled: true

  mongodb:
    host: localhost
    port: 27017
    username: root
    password: root_pass
    database: payment-engine
    authentication-database: admin

  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        auto-startup: false